TTS_dataset: "zenitsu09/CREAMAD-transcribed"

model_name: "canopylabs/orpheus-tts-0.1-pretrained"
epochs: 1
batch_size: 1
number_processes: 1
pad_token: 128263
save_steps: 500
learning_rate: 5.0e-5
save_folder: "checkpoints"
project_name: "tuning-orpheus"
run_name: "5e5-0"